# Generated by Django 4.0.4 on 2022-07-22 09:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0004_defaultpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('gig', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateBlock()), ('link', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock())]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
