# Generated by Django 4.0.4 on 2022-07-22 10:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gigspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigspage',
            name='body',
            field=wagtail.core.fields.StreamField([('gig', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateBlock()), ('link', wagtail.core.blocks.URLBlock()), ('description', wagtail.core.blocks.RichTextBlock())]))]),
        ),
    ]
