# Generated by Django 4.0.4 on 2022-07-22 10:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_gigspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigspage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('gig', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateBlock()), ('link', wagtail.core.blocks.URLBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('private', wagtail.core.blocks.BooleanBlock(default=False))]))]),
        ),
    ]
